INSERT INTO public.users (id, username, password, email, name, surname, gender, personalId, phone, address, city, country, rewardPoints, penaltyPoints, userType, userCategory, verification)VALUES(default, 'user1', '1234', 'user1@gmail.com', 'ivan', 'ivanovic', 'male', '1234567891231', '063123456', 'ulica1', 'novi sad', 'srbija', 0, 0, 'Registered', 'Basic', 'asdfcgasiu');

INSERT INTO public.users (id, username, password, email, name, surname, gender, personalId, phone, address, city, country, rewardPoints, penaltyPoints, userType, userCategory, verification)VALUES(default, 'admin1', '1234', 'admin1@gmail.com', 'pera', 'peric', 'male', '2234567891231', '064123456', 'ulica4124', 'novi sad', 'srbija', null, null, 'Admin', null, 'zxvchuizxv');
insert into public.users (id, username, password, email, name, surname, gender, personalId, phone, address, city, country, rewardPoints, penaltyPoints, userType, userCategory, verification)VALUES(default, 'admin2', '1234', 'admin2@gmail.com', 'joca', 'jocic', 'male', '2234567891231', '064214456', 'ulica34', 'novi sad', 'srbija', null, null, 'Admin', null, 'jkhkljiuhhl');
insert into public.users (id, username, password, email, name, surname, gender, personalId, phone, address, city, country, rewardPoints, penaltyPoints, userType, userCategory, verification)VALUES(default, 'admin3', '1234', 'admin3@gmail.com', 'vuk', 'vucic', 'male', '2234567891231', '064123156', 'ulica1234', 'novi sad', 'srbija', null, null, 'Admin', null, 'xzcvzxasd');
insert into public.users (id, username, password, email, name, surname, gender, personalId, phone, address, city, country, rewardPoints, penaltyPoints, userType, userCategory, verification)VALUES(default, 'admin4', '1234', 'admin3@gmail.com', 'marko', 'markovic', 'male', '2234567891231', '0641777156', 'ulica1274', 'novi sad', 'srbija', null, null, 'Admin', null, 'cvnbcvbnn');

insert into public.companies(id, name, address, openingHours, closingHours, availableEquipment, admins)VALUES(default, 'company1', 'ulica1231', '8:00', '16:00', ARRAY['eq1', 'eq2', 'eq3'], ARRAY['admin1', 'admin2']);  
insert into public.companies(id, name, address, openingHours, closingHours, availableEquipment, admins)VALUES(default, 'company2', 'ulica1271', '9:00', '17:00', ARRAY['eq1', 'eq3'], ARRAY['admin3']);
insert into public.companies(id, name, address, openingHours, closingHours, availableEquipment, admins)VALUES(default, 'company11', 'ulica1891', '9:00', '17:00', ARRAY['eq3'], ARRAY['admin4']);    

insert into public.scheduledpickups(id, equipment, scheduledDate, scheduledTimeStart, scheduledTimeEnd, durationMinutes, company, admins, users)VALUES(default, 'eq1', '2024-06-06', '10:00', '11:00', 60, 'company1', 'admin1', null);
insert into public.scheduledpickups(id, equipment, scheduledDate, scheduledTimeStart, scheduledTimeEnd, durationMinutes, company, admins, users)VALUES(default, 'eq3', '2024-06-06', '12:00', '14:00', 120, 'company1', 'admin1', null);
insert into public.scheduledpickups(id, equipment, scheduledDate, scheduledTimeStart, scheduledTimeEnd, durationMinutes, company, admins, users)VALUES(default, 'eq1', '2024-06-06', '09:00', '10:00', 60, 'company2', 'admin3', null);